apiVersion: v1
data:
  VAULT_ADDR: vault.vault.cluster.svc.local
  AVP_AUTH_TYPE: approle
  AVP_ROLE_ID: 
  AVP_SECRET_ID: 
  AVP_TYPE: vault
kind: Secret
metadata:
  name: vault-configuration
  namespace: argocd
type: Opaque