apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.5.6
- overlays/vault-plugin-cred.yaml
patchesStrategicMerge:
  - overlays/argocd-cm.yaml
  - overlays/repo-server-deployment.yaml
namespace: argocd
images:
  - name: quay.io/argoproj/argocd
    newName: tiwarisanjay/argocd-avp
    newTag: v2.5.6